#!/usr/bin/perl -w

#####################################################
# written by Bob Settlage, DAC, 9 April 2012
# reformats a group of BWA hit files for use with Circos
#
#need list of references and list of files that have hits to those references (generated by BWA followed by awk extraction)
#
#usage perl reformat_awk_BWA.pl references.txt dir_to_scan
#
#####################################################


$refs = $ARGV[0];
$dir_NAME = $ARGV[1];


my @file_ARRAY = `ls $dir_NAME/*sam.txt`; ##readdir '$dir_NAME/*.txt';


##first create hash of references
open (references_FILE, "$refs")|| die "Couldn't open $refs\n";

my %references;
my $temp = <references_FILE>;
while ($temp) {
	chomp $temp;
	$temp =~ s/\>//g;
	$references{$temp} = $temp;
	$temp = <references_FILE>;
}


##now add the tally for each reference for each file
$i=0;
while ($file_ARRAY[$i]) {
	open (tally_FILE, "$file_ARRAY[$i]")|| die "Couldn't open $file_ARRAY[$i]\n";
	foreach $element (keys %references){
		$references{$element} .= " 0";
	}
	my $temp = <tally_FILE>;
	while ($temp) {
		chomp $temp;
		@tmp_count_fields = split(' ', $temp);
		$tmp_count_fields[1] =~ s/\(//g;
		$tmp_count_fields[1] =~ s/\)//g;
		if ($references{$tmp_count_fields[0]}) {
			$references{$tmp_count_fields[0]}= substr($references{$tmp_count_fields[0]},0,-1);
			$references{$tmp_count_fields[0]}.= $tmp_count_fields[1];
		}
		$temp = <tally_FILE>;
	}
	$i++;
}


print "labels";

foreach  (@file_ARRAY) {
	chomp;
	print " " . $_;
}
print "\n";
foreach $element (keys %references){
		print "$references{$element}\n";
	}

exit;